# escape=`
FROM plugins/base:windows-1809-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="drone hue" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-hue.exe C:/bin/drone-hue.exe
ENTRYPOINT [ "C:\\bin\\drone-hue.exe" ]
